### ISSUE TITLE
Bug when deleting scene: "spawn EACCES"

### ISSUE THREAD

**Issue by Fiogan** [ChoicescriptIDE/main#32]
Reported by Alexandria on the CoG forums [here](https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/317?u=fiogan). Opened a new scene 'untitled.txt', tried to delete said scene before adding anything, confirmed deletion on prompt, text box popped up reading 'spawn EACCES'.

**Comment by CareyJWilliams** [comment]
I believe this was already fixed by 8fcb4557384995001afc731e790e3978a244e05f. I'm not sure if this fix is present in an accessible patch, however. I guess that highlights that I need to further improve the commit/patch/update flow!

Will leave this open until we can confirm there's an accessible patch for this.

**Comment by CareyJWilliams** [comment]
Confirmation of a live fix: https://forum.choiceofgames.com/t/cside-the-choicescript-ide/27622/322
